public class InfoCommunities {
	/*
	 
	Depending on the community template the pages are components are different
	The Login and self registration pages are available only when the comminity / site is published
	Make sure you do all the administration setting first to 
		select members
		other settings
	For Search and Dashboards:
		Install managed package : Salesforce Communities Management (for Experience Cloud Sites with Chatter)
	Global search is great component for better search and enhnaced list of objects


	For knowledge:
		Create new text area field on knowledge
		ensure record type for FAQ is created on knowledge
		add new field on knowledge layout
		
		Switch to sf classic and Navigate to Topic for Object and enable topic for Knowledge. Select fields text and title and save.

	 */ 
}