public class InfoECMA6 {
	// Online compiler Javascript: https://onecompiler.com/javascript/3x3ja77wk
    // Javascript Array add , find, remove
    // Use this for learning LWC:
    // https://lwc.dev/guide/html_templates
    // Assignment 1:
    // Create Apex class , add a function to Create Accounts (param )
    // 
   /* 
    let arr1 = [{'name':'Abhay', 'standard': 5},
    {'name':'Ajay', 'standard': 6},
    {'name':'Nitesh', 'standard': 7},
    {'name':'Yogesh', 'standard': 8}];
    
    arr1.push({'name':'David', 'standard': 7});
    console.log(arr1);
    
    for(element in arr1){
     // console.log(element , ' :: ', arr1[element]);
    }
    
    let nm = 'Yogesh';
    
    let found = arr1.findIndex(key => key.name === nm);
      console.log('found -> ', found);
    arr1.splice(found,1);
    console.log(arr1); 
*/
    
}