public class INFOSFKBase {
/*
Good to Read
    https://salesforceben.com/guide-to-5-types-of-salesforce-architects/
	
Get to know Salesforce shield, its usage and implementation use cases from below excellent learning resources.
 	https://shieldlearningmap.com/

Get to know about Salesforce Integration and API's, its usage and implementation use cases from below excellent learning resources.
	https://developer.salesforce.com/developer-centers/integration-apis/

Kickstart your journey building with Identity. Get started with some quick Identity-focused tutorials. Dig in to the nuts and bolts of Identity with reference docs.
	https://developer.salesforce.com/developer-centers/identity/

Salesforce Objects:
https://www.salesforce.com/video/7831966/

Kickstart your journey building with Lightning Apps 
	https://developer.salesforce.com/developer-centers/lightning-apps/


*/
}