public class InfoProjectTask {
   //https://live.playg.app/play/flow-create-update-custom-metadata
  // Create custom hierarchy
  // DynamicTreeStructure and TreeStructure  
 /*
  * 
  1. Batch Process Progress check using platform event: 
		LWC: batchProgress, class, batch
	Please read the problem carefully and then you need to solve the below problem within 2 weeks. No Solution will be considered valid if you are submitting the solution after 2 weeks.



You can get all the objects from Here.



Objects Available in the Org



Project
MileStone
Project Tasks
Project Logs
Time Sheet
Where Project is the Parent object and Milestone is the Child Object.



Milestone is the Parent and Project Task and Project Logs are Child Object.



Project Task is the Parent Object and Time Sheet is the child Object.



Problem: (Must to Have)-



Probelm1 - You need to develop a lightning web component that will be sitting on the Project Record Detail Page.



The component will have a list of all the tasks related to that Projects Milestone record.



When the End User selects any task it should display all the TimeSheet entries related to that task in the editable form. So that user can make the modification in the timesheet.
Only the Current Week timesheet should be editable and the previous week and coming week timesheet should be disabled.
There should be only one timesheet for a week for every developer under a single task.
When a user modifies or added new hours. After clicking on Update/Create it should make the necessary changes into the Timesheets related to that task.
When the Timesheet entry is created into the System then the sum of all days ( weekdays) work must be reflected in the Hours Worked field on the Time Sheet object.
All the Timesheets "Hours Worked" must be rolled up to the Actual Hours field for the related Task Record.
While Creating the Time Sheet Entry Record it must associate the Related Project & MileStone.
All the triggers and Apex Class must have test classes.


Problem2 (Good To Have) - This is the Optional part of the Assessment but good to have. Create a Lightning Dashboard that will tell the status of a project and Add that Dashboard to the Project Record Page. Functionalities good to have

Project MileStone Status
Tasks By Owner
Over Due Tasks
Project Task Estimated Hours vs Actual Hours


Problem3 - Good to have:-

Develop a Lightning Web Component that displays all the Tasks for the Logged In Users in the form of a Calendar. You can take helo from This Blog Post. And Add this Component to Home Page. Also, Give the Ability to Select the Project as well.



Note: - Prepare an Unmanaged package that contains the component which you have developed. Do not include the Component from the above package.



If you are still confused then send me an email to sfdcpanther@gmail.com
*/
}